### ISSUE TITLE
AUI WebJar 5.7.19 and 5.8.1 are pointing to wrong repo?

### ISSUE THREAD

**Issue by naderghanbari** [webjars/aui#3]
It seems that prior version 5.7.19 (5.6.x for instance), AUI WebJar was pointing to [https://bitbucket.org/atlassian/aui-dist](aui-dist) but now it's pointing to [https://bitbucket.org/atlassian/aui](aui) repo which contains sources. 

As a result the artifact now contains source files (less files, build files, etc.) instead of dist files (css files).

**Comment by jamesward** [comment]
For `5.8.1` it is pointing to the `aui-dist` repo: https://github.com/webjars/aui/blob/aui-5.8.1/pom.xml#L51

Am I reading your comment wrong?  Are we pointing to the wrong dist download somehow?

**Comment by naderghanbari** [comment]
I've seen it in pom.xml (pointing to aui-dist) but somehow the resulting artifact does not contains dist files.  Instead it contains the whole source tree of [https://bitbucket.org/atlassian/aui](https://bitbucket.org/atlassian/aui) and not aui-dist.

**Comment by jamesward** [comment]
I just compared http://www.webjars.org/listfiles/aui/5.8.1 with https://bitbucket.org/atlassian/aui-dist/get/5.8.1.zip and they are exactly the same.

**Comment by naderghanbari** [comment]
True they are exactly the same. It seems that the problem is due to https://bitbucket.org/atlassian/aui-dist/get not serving the dist files but the source files (from https://bitbucket.org/atlassian/aui repo)
